name: Build & Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write   # allow workflow to create releases

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Build installer
        run: npm run dist

      - name: Upload artifacts to Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/*.exe
            release/*.yml
            release/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
